/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * MCP server connection entry.
 */
export interface McpServerEntry {
    /**
     * Transport type (stdio or http).
     */
    'type'?: string;
    /**
     * Command and arguments for stdio transport.
     */
    'command'?: Array<string>;
    /**
     * Environment variables for stdio transport.
     */
    'env'?: { [key: string]: string; };
    /**
     * URL for http transport.
     */
    'url'?: string;
    /**
     * HTTP headers for http transport.
     */
    'headers'?: { [key: string]: string; };
    /**
     * Startup timeout in seconds.
     */
    'startup_timeout_secs'?: number;
    /**
     * Tool call timeout in seconds.
     */
    'tool_timeout_secs'?: number;
}

