/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HookDefinition } from './hook-definition';
// May contain unused imports in some cases
// @ts-ignore
import type { LlmConfiguration } from './llm-configuration';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxConfiguration } from './sandbox-configuration';
// May contain unused imports in some cases
// @ts-ignore
import type { SetupConfiguration } from './setup-configuration';

/**
 * Structured run configuration mirroring WorkflowRunConfig.
 */
export interface RunConfiguration {
    /**
     * Configuration schema version.
     */
    'version': number;
    /**
     * Goal description for the run.
     */
    'goal'?: string;
    /**
     * DOT graph filename.
     */
    'graph': string;
    /**
     * Working directory for the run.
     */
    'work_dir'?: string;
    'llm'?: LlmConfiguration;
    'setup'?: SetupConfiguration;
    'sandbox'?: SandboxConfiguration;
    /**
     * Variable map for template expansion.
     */
    'vars'?: { [key: string]: string; };
    'hooks'?: Array<HookDefinition>;
}

