/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Summary of a session shown in list views.
 */
export interface SessionListItem {
    /**
     * Unique session identifier.
     */
    'id': string;
    /**
     * Short title summarizing the session topic.
     */
    'title': string;
    /**
     * ISO 8601 timestamp when the session was created.
     */
    'created_at': string;
}

