/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ToolUse } from './tool-use';

/**
 * A single turn in a session conversation — a user message, assistant response, or tool invocation block.
 */
export interface SessionTurn {
    /**
     * The type of turn.
     */
    'kind': SessionTurnKindEnum;
    /**
     * Text content of the turn. Present for user and assistant turns, absent for tool turns.
     */
    'content'?: string;
    /**
     * ISO 8601 timestamp when the turn was created. Typically present for user turns.
     */
    'created_at'?: string;
    /**
     * Tool invocations for this turn. Present only when kind is \"tool\".
     */
    'tools'?: Array<ToolUse>;
}

export const SessionTurnKindEnum = {
    USER: 'user',
    ASSISTANT: 'assistant',
    TOOL: 'tool'
} as const;

export type SessionTurnKindEnum = typeof SessionTurnKindEnum[keyof typeof SessionTurnKindEnum];


